### ISSUE TITLE
Build fails - missing header file

### ISSUE THREAD

**Issue by JamesBremner** [C0smicCrush/Vectors-Graph-Theory-Implementation#1]
```
main.cpp:1:10: fatal error: main.h: No such file or directory
    1 | #include "main.h"
```

**Comment by JamesBremner** [comment]
This problem has not been fixed!

**Comment by C0smicCrush** [comment]
main.h is in the files, I don't understand why this error is happening. I'm running the program in the CLI and it seems to be working fine.

**Comment by JamesBremner** [comment]
It was not fixed 7 hours ago.  It looks like you have added the missing header, so you can close this one now

**Comment by C0smicCrush** [comment]
I'm happy it works 😀
closing this now
