### ISSUE TITLE
LinkedList::returnArray

### ISSUE THREAD

**Issue by JamesBremner** [C0smicCrush/Vectors-Graph-Theory-Implementation#10]
```
void LinkedList::returnArray(int* inArr){
 	int count = getCount();
 	Node* pos = head;
 	for(int x =0; x < count; x++){
 		*(inArr+x) = pos->data.id;
 		pos = pos->next;
	 }
 }
```

1. The name of this method is misleading.  It returns void.
2. The call to getCount() is extremely expensive.  It steps through every member of the list!
3. The code will crash if the array has not been correctly allocated

I would suggest refactoring this to be faster and easier to understand

```
void LinkedList::fillArray(
int* inArr, int length ){
        
// start at the begining of the list
 	Node* pos = head;

// loop until the end is reached
        while( pos ) {

// copy data into next array position
 		*(inArr++) = pos->data.id;

// step to next list position
 		pos = pos->next;

// check we have been promised a sufficient large array
         if( --length <= 0 )
               throw std::runtime_error(
                   "LinkedList::fillArray overflow");
	 }
 }
```

**Comment by C0smicCrush** [comment]
Oh hey, I had a test yesterday so I didn't really do anything. Do you suggest I create a getCount which is an attribute of the class instead of being this way? Like, i have an int count and such? Yea, I'll fix these errors but I may be a bit slow to respond since I'm on vacation rn

**Comment by C0smicCrush** [comment]
Fixed getCount() to be a returning of member  count

**Comment by C0smicCrush** [comment]
I fixed the code, also, we don't need to check for the length of the array because we already have getCount, so by checking length we're essentially doing the same thing twice. getCount is much less resource intensive now!
