### ISSUE TITLE
Bug in clearGraph()

### ISSUE THREAD

**Issue by JamesBremner** [C0smicCrush/Vectors-Graph-Theory-Implementation#5]
https://github.com/atomind2005/Vectors-Graph-Theory-Implementation/blob/4bcddc3882eddd4fc1d603cacc0c8334f3efbaf3/Graph.cpp#L265-L269

You need to set the attributes vertices and edges to zero.

**Comment by C0smicCrush** [comment]
I removed edges attribute and created a  method to return edges. Vertices are now set to 0 in clearGraph()  :D

**Comment by JamesBremner** [comment]
https://github.com/atomind2005/Vectors-Graph-Theory-Implementation/blob/d68d5a38d8fcf6473d45c140160cad7daae08583/Graph.h#L17

The edges attribute is till there.  Please do not close issues before they are fixed.

**Comment by C0smicCrush** [comment]
Oh, my bad, I fixed it now I think
