### ISSUE TITLE
Order of includes

### ISSUE THREAD

**Issue by JamesBremner** [C0smicCrush/Vectors-Graph-Theory-Implementation#8]
https://github.com/atomind2005/Vectors-Graph-Theory-Implementation/blob/038eea8152730d4178b9ab144e532691798f8f3c/Graph.h#L8-L12

The order of` #include` statements is important.

Never include your application header files BEFORE the standard headers.

**Comment by C0smicCrush** [comment]
I didn't know that, thanks for telling me! I've fixed it now😀
