### ISSUE TITLE
Problem in main.cpp

### ISSUE THREAD

**Issue by JamesBremner** [C0smicCrush/Vectors-Graph-Theory-Implementation#9]
https://github.com/atomind2005/Vectors-Graph-Theory-Implementation/blob/038eea8152730d4178b9ab144e532691798f8f3c/main.cpp#L1

What is this?!?!

And this?

https://github.com/atomind2005/Vectors-Graph-Theory-Implementation/blob/038eea8152730d4178b9ab144e532691798f8f3c/main.cpp#L10

You should ALWAYS do a test build before you commit code, to prevent mistakes like this.

**Comment by C0smicCrush** [comment]
Yea, I'm sorry about that. I tried to fix the merge thing but I think I forgot to remove those. I've fixed it!

**Comment by JamesBremner** [comment]
If you do a test build before committing things like that are never "forgotten"

**Comment by C0smicCrush** [comment]
Oh ok, how would I do that? Like, how do I make a test build? Would I have another branch for it or is it just tested locally?

**Comment by JamesBremner** [comment]
Run the makefile and check the compiler does not produce any errors

Here is how I do it:

```
> Executing task: C:\Users\James\code\ext\msys64\mingw64\bin\mingw32-make.exe -f makefile.mk test <

g++ -o  obj/main.o -c main.cpp -I./ -std=c++17 -g
g++ -o  obj/graph.o -c graph.cpp -I./ -std=c++17 -g
graph.cpp: In member function 'bool Graph::removeEdge(int, int)':
graph.cpp:241:1: warning: control reaches end of non-void function [-Wreturn-type]
  241 | }
      | ^
graph.cpp: In member function 'bool Graph::disconnectedHelper(int)':
graph.cpp:76:17: warning: 'void operator delete(void*, std::size_t)' called on unallocated object 'stack' [-Wfree-nonheap-object]
   76 |         delete &stack;
      |                 ^~~~~
graph.cpp:54:15: note: declared here
   54 |         Stack stack(vertices);
      |               ^~~~~
g++ -o  obj/stack.o -c stack.cpp -I./ -std=c++17 -g
g++ -o  obj/linkedlist.o -c linkedlist.cpp -I./ -std=c++17 -g
g++ -o ../bin/test.exe \
        ./obj/main.o ./obj/graph.o ./obj/stack.o ./obj/linkedlist.o  -static-libstdc++ -static-libgcc -static -g
```

**Comment by C0smicCrush** [comment]
Oh ok, I just run g++ -I *./ *.cpp on my CLI and then run the executable. Are there any particulars you'd suggest?
